# Site settings
author: Shaquille Galimba
title: Ang paglalakbay
header-img: img/home-bg.png
email: shaqrivergalimba24@gmail.com
copyright_name: Shaquille Galimba
description: > # this means to ignore newlines until "baseurl:"
  My continuous pursuit of learning.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  shaquille-galimba

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
